---
title: "Untitled"
output: html_document
date: '2024-01-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Experiment 1: SC-CP
```{r}
library(data.table)
library(ggplot2)
library(latex2exp)
out <- rbindlist(lapply(c(1, 1.5, 2, 2.5, 3), function(shape) {
  data <- fread(paste0("results/sims_calibration_1000_rf_5_0.1_", shape, "_0.6.csv"))
  data$shape <- shape
  data
}))


method_names <- c("HistCAL-CP (5 bins)", "Cond-CP", "SC-CP (ours)", "Uncond-CP", "Mondrian-CP", "Oracle")
names(method_names) <- c("cal_binning_1", "conditional", "isotonic","marginal", "mondrian_1", "oracle")

out <- out[out$method %in% c("mondrian_1", "marginal", "isotonic", "conditional", "oracle")]

out$method <- method_names[match(out$method, names(method_names))]

out$method <- factor(out$method, levels = 
                     c("SC-CP (ours)", "Cond-CP" , "Uncond-CP", "HistCAL-CP (5 bins)", "Mondrian-CP", "Oracle")  )

out[,  shape_error := cal_error[method == "Uncond-CP" & bin == "marginal"], by = shape]
 
 
plt1 <- ggplot(out[out$bin == "marginal"], aes(x = shape_error, y = width, color = method)) + geom_point(aes(shape = method), size = 4)   + theme_bw() + labs(x = TeX("Calibration error in f( )"), y = "Interval Width ($\\alpha = 0.1$)") +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank())) + 
 theme(legend.text = element_text(size = 11), legend.key.size = unit(2, "lines"))

 
plt1
ggsave("plots/calibration_shift.pdf" , width = 6, height =4)
 
```


## Experiment 2: calibration for scoring function
```{r}
library(latex2exp)

results_1 <- rbindlist(readRDS("results/calerror_1.rds"))
results_1 <- results_1[, .(width = mean(width), cal_error = mean(cal_error)), by = c("shape", "alpha", "Status")]
results_1 <- results_1[, .(relative = width[Status=="Calibrated"] / width[Status=="Uncalibrated"]) , by = c("cal_error", "alpha")]
 



results_2 <- readRDS("results/calerror_2.rds")
results_2 <- results_2[, .(width = mean(width)), by = c("n", "alpha", "Status")]
results_2 <- results_2[, .(relative = width[Status=="Calibrated"] / width[Status=="Uncalibrated"]) , by = c("n", "alpha")]

 
results_1$alpha <- factor(results_1$alpha, levels = c(0.05, 0.1, 0.2))
results_2$alpha <- factor(results_2$alpha, levels = c(0.05, 0.1, 0.2))
 

library(latex2exp)
 
plt1 <- ggplot(results_1 , aes(x = cal_error, y = relative, color = (alpha), linetype = (alpha))) + geom_line() +
  theme_bw() + labs(y = TeX("Relative Width (cal/uncal)"), x = TeX("Calibration error of f ($\\n_{Cal} = 1000)"),
                    color = "Sig. Level", linetype = "Sig. Level") +
  geom_hline(yintercept = 1, color = "black", linetype = "dashed" , alpha = 0.5) + scale_y_continuous(limits = c(0.7, 1.2))  

 
plt2 <- ggplot(results_2 , aes(x = n, y = relative, color = (alpha), linetype = (alpha))) + geom_line() +
  theme_bw() + labs(y = TeX("Relative Width (cal/uncal)"), x = TeX("Calibration set size ($kappa_{train} = 3$)"), color = "Sig. Level", linetype = "Sig. Level") + scale_x_log10() +
  geom_hline(yintercept = 1, color = "black", linetype = "dashed" , alpha = 0.5) + scale_y_continuous(limits = c(0.7, 1.2)) 


library(patchwork)
combined_plot <- (plt1 + plt2)  + plot_layout(guides = "collect", axis_titles = "collect", axes = "collect") & theme(legend.position = "bottom") #+  labs(color = TeX("$\\alpha$"), linetype = TeX("$\\alpha$"))
combined_plot
print(combined_plot)

ggsave("plots/calibration_shift_2.pdf", plot = combined_plot, width = 6, height = 4)
# this plot is good


 
```



 

 
 

 

## Experiment 2: good example

```{r}
library(data.table)
library(ggplot2)
library(latex2exp)
method_names <- c("HistCAL (5 bins)", "Cond-CP", "SC-CP (ours)", "Uncond-CP", "Mondrian-CP", "Oracle")
names(method_names) <- c("cal_binning_5", "conditional", "isotonic","marginal", "mondrian_1", "oracle")
a <- 0
b <- 0.6
out <- fread(paste0("results/sims_coverage_1000_gam_5_0.1_1_", b, "_", a, ".csv"))
#out <- fread(paste0("results/sims_calibration_1000_rf_5_0.1_1_0.6.csv"))

out <- out[out$method %in% c("oracle",   "mondrian_1", "marginal", "isotonic", "conditional")]
out$method <- method_names[match(out$method, names(method_names))]

out$method <- factor(out$method, levels = 
                     c("SC-CP (ours)", "Cond-CP" , "Uncond-CP", "HistCAL (5 bins)", "Mondrian-CP", "Oracle")  )



plot1 <- ggplot(out , aes(x = bin, y = coverage, color = method)) + geom_point(aes(shape = method), size = 3) + theme_bw() + labs(y = TeX("Coverage ($\\alpha = 0.1$)"), x = TeX("Quintiles of $\\sigma^2(X)$")) + scale_x_discrete(labels = c("Q.1", 
                                                       "Q.2",
                                                       "Q.3",
                                                       "Q.4",
                                                       "Q.5",
                                                       "Uncond."))  +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank()))  + geom_vline(xintercept = 5.5, alpha = 0.3, linetype = "dashed") + geom_hline(yintercept = 0.9, alpha = 0.5, color = "red")


plot2 <- ggplot(out , aes(x = bin, y = width, color = method)) + geom_point(aes(shape = method), size = 3)   + theme_bw() + labs(y = "Interval Width", x = TeX("Quintiles of $\\sigma^2(X)$")) + scale_x_discrete(labels = c("Q.1", 
                                                       "Q.2",
                                                       "Q.3",
                                                       "Q.4",
                                                       "Q.5",
                                                       "Uncond."))   +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank()))  + geom_vline(xintercept = 5.5, alpha = 0.3, linetype = "dashed")

library(patchwork)
combined_plot <- plot1 + plot2 + plot_layout(guides = "collect") & theme(legend.position = "bottom")
combined_plot
print(combined_plot)

ggsave("plots/conditional_coverage.pdf", plot = combined_plot, width = 6, height = 3.5)
# this plot is good


plot1 + plot2 + plot_layout(guides = "collect") & theme(legend.position = "bottom")
```
## Experiment 2: good example high d

```{r}
library(data.table)
library(ggplot2)
library(latex2exp)
method_names <- c("HistCAL (5 bins)", "Cond-CP", "SC-CP (ours)", "Uncond-CP", "Mondrian-CP", "Oracle")
names(method_names) <- c("cal_binning_5", "conditional", "isotonic","marginal", "mondrian_1", "oracle")
a <- 0
b <- 0.6
out <- fread(paste0("results/sims_coverage_1000_gam_20_0.1_1_", b, "_", a, ".csv"))
#out <- fread(paste0("results/sims_calibration_1000_rf_5_0.1_1_0.6.csv"))

out <- out[out$method %in% c("oracle",   "mondrian_1", "marginal", "isotonic", "conditional")]
out$method <- method_names[match(out$method, names(method_names))]

out$method <- factor(out$method, levels = 
                     c("SC-CP (ours)", "Cond-CP" , "Uncond-CP", "HistCAL (5 bins)", "Mondrian-CP", "Oracle")  )



plot3 <- ggplot(out , aes(x = bin, y = coverage, color = method)) + geom_point(aes(shape = method), size = 3) + theme_bw() + labs(y = TeX("Coverage ($\\alpha = 0.1$)"), x = TeX("Quintiles of $\\sigma^2(X)$")) + scale_x_discrete(labels = c("Q.1", 
                                                       "Q.2",
                                                       "Q.3",
                                                       "Q.4",
                                                       "Q.5",
                                                       "Uncond."))  +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank()))  + geom_vline(xintercept = 5.5, alpha = 0.3, linetype = "dashed") + geom_hline(yintercept = 0.9, alpha = 0.5, color = "red")


plot4 <- ggplot(out , aes(x = bin, y = width, color = method)) + geom_point(aes(shape = method), size = 3)   + theme_bw() + labs(y = "Interval Width", x = TeX("Quintiles of $\\sigma^2(X)$")) + scale_x_discrete(labels = c("Q.1", 
                                                       "Q.2",
                                                       "Q.3",
                                                       "Q.4",
                                                       "Q.5",
                                                       "Uncond."))   +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank()))  + geom_vline(xintercept = 5.5, alpha = 0.3, linetype = "dashed")

library(patchwork)
combined_plot <- plot3 + plot4 + plot_layout(guides = "collect") & theme(legend.position = "bottom")
combined_plot
print(combined_plot)

ggsave("plots/conditional_coverage_highd.pdf", plot = combined_plot, width = 6, height = 3.5)
# this plot is good


plot1 <- plot1 + ggtitle("d=5")
plot3 <- plot3 + ggtitle("d=20")

combined_plot <- plot1 + plot2+ plot3+ plot4 + plot_layout( guides = "collect", axis_titles ="collect") & theme(legend.position = "bottom") 


ggsave("plots/conditional_coverage_both.pdf", plot = combined_plot, width = 6, height = 6)

```


## Experiment 2: bad example

```{r}
library(data.table)
library(ggplot2)
library(latex2exp)
method_names <- c("HistCAL (5 bins)", "Cond-CP", "SC-CP (ours)", "Uncond-CP", "Mondrian-CP", "Oracle")
names(method_names) <- c("cal_binning_5", "conditional", "isotonic","marginal", "mondrian_1", "oracle")
a <- 0.6
b <- 0
out <- fread(paste0("results/sims_coverage_1000_gam_5_0.1_1_", b, "_", a, ".csv"))
#out <- fread(paste0("results/sims_calibration_1000_rf_5_0.1_1_0.6.csv"))

out <- out[out$method %in% c("oracle",   "mondrian_1", "marginal", "isotonic", "conditional")]
out$method <- method_names[match(out$method, names(method_names))]

out$method <- factor(out$method, levels = 
                     c("SC-CP (ours)", "Cond-CP" , "Uncond-CP", "HistCAL (5 bins)", "Mondrian-CP", "Oracle")  )



plot5 <- ggplot(out , aes(x = bin, y = coverage, color = method)) + geom_point(aes(shape = method), size = 3) + theme_bw() + labs(y = TeX("Coverage ($\\alpha = 0.1$)"), x = TeX("Quintiles of $\\sigma^2(X)$")) + scale_x_discrete(labels = c("Q.1", 
                                                       "Q.2",
                                                       "Q.3",
                                                       "Q.4",
                                                       "Q.5",
                                                       "Uncond."))  +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank()))  + geom_vline(xintercept = 5.5, alpha = 0.3, linetype = "dashed") + geom_hline(yintercept = 0.9, alpha = 0.5, color = "red")


plot6 <- ggplot(out , aes(x = bin, y = width, color = method)) + geom_point(aes(shape = method), size = 3)   + theme_bw() + labs(y = "Interval Width", x = TeX("Quintiles of $\\sigma^2(X)$")) + scale_x_discrete(labels = c("Q.1", 
                                                       "Q.2",
                                                       "Q.3",
                                                       "Q.4",
                                                       "Q.5",
                                                       "Uncond."))   +   guides(color = guide_legend(title = element_blank()), shape = guide_legend(title = element_blank()))  + geom_vline(xintercept = 5.5, alpha = 0.3, linetype = "dashed")

library(patchwork)
combined_plot <- plot5 + plot6 + plot_layout(guides = "collect") & theme(legend.position = "")
combined_plot
print(combined_plot)

ggsave("plots/conditional_coverage_adverserial.pdf", plot = combined_plot, width = 6, height = 3.5)
# this plot is good


 
```


```{r}



plot1 <- plot1 + ggtitle("Setup A (d=5)")
plot3 <- plot3 + ggtitle("Setup B (d=20)")
plot5 <- plot5 + ggtitle("Setup C (adverserial, d=5)")
combined_plot <- plot1 + plot2+ plot3+ plot4 + plot5 + plot6+ plot_layout(ncol =2, guides = "collect", axis_titles ="collect") & theme(legend.position = "bottom") 


ggsave("plots/conditional_coverage_triple.pdf", plot = combined_plot, width = 6, height = 8)


```

