site_name: Self-Calibrating Conformal
site_url: https://larsvanderlaan.github.io/SelfCalibratingConformal/
theme:
  name: material
  palette:
    primary: teal
    accent: amber
nav:
  - Home: index.md
  - API: api.md
  - Guides: guides.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
