---
title: "Untitled"
output: html_document
date: '2024-01-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(data.table)
library(ggplot2)
library(latex2exp)
data <- rbindlist(lapply(c( 50, 100, 300, 1000), function(n) {
  data <- read.csv(paste0("plots/curves_", n, "_0.5.csv"))
  data$n <- n
  return(data)
}))
data[data$method == "isotonic", "method"] <- "SC-CP (ours)"
#data[data$method == "isotonic", "method"] <- "Isotonic (ours)"
#data[data$method == "conditional", "method"] <- "Conditional (Gibbs)"
data[data$method == "conditional", "method"] <- "Cond-CP"
data[data$method == "marginal", "method"] <- "Uncond-CP"

alpha <- 0.1
n_test <- 1000
data_list <- generate_data_splits(1000,  1000, n_test = 1000, d = 1, distr_shift = TRUE, shape = 1, b = 0.5)
data_test <- data_list$data_test


preds_oracle <- data.table(X = as.vector(data_test$X),
                           f = data_test$mu, 
                           lower = qnorm(0.05, data_test$mu, data_test$sigma),
                           upper = qnorm(0.95, data_test$mu, data_test$sigma),
                           method = "Oracle")


 

data$method <- factor(data$method, levels = c("SC-CP (ours)", "Cond-CP", "Uncond-CP"))

appender <- function(string) {
    TeX(paste("$n_{cal} = $", string)) 
}
preds_oracle <- rbindlist(lapply(sort(unique(data$n)), function(n) {
  dat <- copy(preds_oracle)
  dat$n <- n
  dat
}))
data_all <- rbind(data[, c("n", "X", "f", "lower", "upper", "method"), with = FALSE], preds_oracle)
plt <- ggplot(data_all, aes(x = X, color = method, linetype = method)) +
  geom_step(aes(y = lower), size = 0.8)  +
  geom_step(aes(y = upper), size = 0.8) +
 # geom_line(data = preds_oracle, aes(x = X, y = lower), color = "black", alpha = 1, linetype = "solid")  +
#  geom_line(data = preds_oracle, aes(x = X, y = upper), color = "black", alpha = 1, linetype = "solid") +
  theme(legend.position="bottom") + theme_bw() + labs(x = "Covariate (X)", color = "", y = "Outcome (Y)") + facet_wrap(~ n, labeller = as_labeller(appender, 
                            default = label_parsed) ) +  labs(color  = "", linetype = "", shape = "")   + theme(legend.key.size = unit(1, "cm"), 
        legend.text = element_text(size = 12),  # Adjust text size here
        legend.title = element_text(size = 14), # Adjust title size here
        legend.position = "bottom", 
        legend.direction = "horizontal",
        legend.margin = margin(0,0,0,0),
        legend.box.margin = margin(-10,-10,-10,-10)) +
  scale_linetype_manual(values = c("solid", "dotted", "dashed", "dotdash"))

#theme(legend.key.size = unit(1, "cm"), legend.position = "bottom", legend.direction = "horizontal",
                                                                                            #  legend.margin=margin(0,0,0,0),
    #    legend.box.margin=margin(-10,-10,-10,-10))  +
  #scale_linetype_manual(values=c("solid", "dotted", "dashed", "dotdash"))  

plt


ggsave(file="plots/curves_pooled.pdf", width=7, height=5)
# 
# plt <- ggplot(data, aes(x = X, color = method, linetype = method)) +
#   geom_step(aes(y = lower), size = 0.8)  +
#   geom_step(aes(y = upper), size = 0.8) +
#   theme(legend.key.size = unit(1, "cm"), legend.direction = "horizontal")  +
#   scale_linetype_manual(values=c("solid", "dotted", "dashed", "dotdash")) +
#   labs(color  = "", linetype = "", shape = "")  
# 
# library(cowplot)
# library(grid)
# legend <-  get_legend(plt)
# pdf("plots/curves_pooled_legend.pdf", width = 5, height = 1) # Adjust the width and height as needed
# grid.draw(legend)
# dev.off()
# 
#  
#X_grid <- seq(0, 1, length = 10000)

# new_data <- rbindlist(unlist(lapply(unique(data$method), function(method) {
#   lapply(unique(data$n), function(n) {
#     data_sub <- data[data$method == method & data$n == n,]
#     if(method == "isotonic") { 
#       x_sort <- data_sub$X[order(data_sub$X)]
#       lower_sort <- data_sub$lower[order(data_sub$X)][!duplicated(x_sort)]
#       upper_sort <- data_sub$upper[order(data_sub$X)][!duplicated(x_sort)]
#       x_sort <- x_sort[!duplicated(x_sort)]
#       
#       fit_lower <- stepfun(x_sort, c(lower_sort, lower_sort[length(lower_sort)]))
#       fit_upper <- stepfun(x_sort, c(upper_sort, upper_sort[length(upper_sort)]))
#     } else {
#       fit_lower <- ksmooth(x = data_sub$X, y = data_sub$lower, range.x = c(0,1), n.points = 1000, kernel = "normal")
#       fit_upper <- ksmooth(x = data_sub$X, y = data_sub$upper, range.x = c(0,1), n.points = 1000, kernel = "normal")
#       
#       new_data <- data.table(method = method, n = n, X = fit_lower$x, 
#                              lower = fit_lower$y,
#                              upper = fit_upper$y
#       )
#     }
#     
#     
#     return(new_data)
#   })}), recursive = FALSE))
# 
# 


#ggsave(file="plots/curves_pooled_legend.pdf", width=7, height=5)
 

```

